import type { Metadata } from "next";
import localFont from "next/font/local";
import { ChakraProvider } from '@chakra-ui/react'
import Footer from "@/app/components/Footer"
import { theme } from "@/app/theme/extendTheme";
import { Header } from "./components/Header/Header";

import "./global.scss"

const myFont = localFont({
  src: [
    {
      path: '../app/assets/fonts/light.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: '../app/assets/fonts/regular.ttf',
      weight: '400',
      style: 'italic',
    },
    {
      path: '../app/assets/fonts/semi_inter_bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: '../app/assets/fonts/big_bold.ttf',
      weight: '700',
      style: 'italic',
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <ChakraProvider resetCSS theme={theme.color}>
          <Header/>
        {children}
        <Footer/>
        </ChakraProvider>
      </body>
    </html>
  );
}
